export enum Milestone {
  DISPATCH_ASSIGNED = 'DISPATCH_ASSIGNED',
  EN_ROUTE_TO_PICKUP = 'EN_ROUTE_TO_PICKUP',
  ARRIVED_AT_PICKUP = 'ARRIVED_AT_PICKUP',
  LOADING_STARTED = 'LOADING_STARTED',
  LOADING_FINISHED = 'LOADING_FINISHED',
  DISPATCHED = 'DISPATCHED',
  EN_ROUTE_TO_DESTINATION = 'EN_ROUTE_TO_DESTINATION',
  ARRIVED_AT_DESTINATION = 'ARRIVED_AT_DESTINATION',
  UNLOADING_STARTED = 'UNLOADING_STARTED',
  UNLOADING_FINISHED = 'UNLOADING_FINISHED',
  COMPLETED = 'COMPLETED'
}

export const MILESTONE_SEQUENCE: Milestone[] = [
  Milestone.DISPATCH_ASSIGNED,
  Milestone.EN_ROUTE_TO_PICKUP,
  Milestone.ARRIVED_AT_PICKUP,
  Milestone.LOADING_STARTED,
  Milestone.LOADING_FINISHED,
  Milestone.DISPATCHED,
  Milestone.EN_ROUTE_TO_DESTINATION,
  Milestone.ARRIVED_AT_DESTINATION,
  Milestone.UNLOADING_STARTED,
  Milestone.UNLOADING_FINISHED,
  Milestone.COMPLETED
];
